stages:
  - deploy

variables:
  PM2_APP_NAME: "your_app_name"

deploy:
  stage: deploy
  script:
    - npm install
    - pm2 delete $PM2_APP_NAME || true
    - pm2 start npm --name $PM2_APP_NAME -- run start
